dist: trusty

osx_image: xcode8.3

sudo: false

language: cpp

addons:
  apt:
    packages: &default_packages
      - cmake
      - libmicrohttpd-dev
      - libssl-dev
      - libhwloc-dev

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *default_packages
            - gcc-7
            - g++-7
      env:
        - CONFIG_ID=1
        - CMAKE_CXX_COMPILER=g++-7
        - CMAKE_C_COMPILER=gcc-7

#    - os: osx
#      compiler: gcc

before_install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew tap homebrew/science; fi

script:
  - if [ $TRAVIS_OS_NAME = osx ]; then
      brew install hwloc;
      cmake -DMICROHTTPD_ENABLE=OFF -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl .;
    else
      cmake -D CMAKE_C_COMPILER=${CMAKE_C_COMPILER} -D CMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER} .;
    fi;
  - make VERBOSE=1
  - mv ./bin/xmr-stak-cpu ./bin/testsuites
  - ./bin/testsuites -c ./configs/config.txt
